production:
  type: git
  source: https://github.com/nwops/kontrol-repo-yaml.git
  version: main
  
# the r10k settions must first ignore the production branch and run puppet agent to configure the settings
# once completed you can specify production here
